modLoader="javafml"
loaderVersion="[36,)"
license="GNU General Public License version 3 (GPLv3)"

[[mods]]
modId="nomorephantoms"
version="1.0.0"
displayName="NoMorePhantoms"
credits="Thank's for downloading this mod!"
displayURL="https://mcreator.net"
authors="GamingBurber"
description='''
Turns off Phantom Spawning.
'''

[[dependencies.nomorephantoms]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




